# Generated by Django 4.2 on 2023-07-26 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(1, 'Title must be greater than 5 characters')])),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tags'),
        ),
    ]
